// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6851.RobotBuildCompe2019.subsystems;


import org.usfirst.frc6851.RobotBuildCompe2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.TalonSRX;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.can.*;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Elevator extends Subsystem {
    public static final double kiCountPerTurn = 40960;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private TalonSRX ascenceur1;
    private TalonSRX ascenceurPourche;
    private DigitalInput limitSwitch1;
    private DigitalInput limitSwitch2;
    private Relay tombePourche;
    private TalonSRX Elevateur1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Elevator() {
        // TALONSRX TEST
        //TalonSRX mytalon = new TalonSRX(4);
        //mytalon.set(ControlMode.PercentOutput,0);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        ascenceur1 = new TalonSRX(4);
        ascenceur1.set(ControlMode.PercentOutput,0.1);
        ascenceur1.selectProfileSlot(0,0);
        ascenceur1.setInverted(false);
        //addChild("Ascenceur1",ascenceur1);
        //ascenceur1.setInverted(false);
        ascenceur1.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder);
        ascenceur1.getSensorCollection().setQuadraturePosition(0,100);
        ascenceur1.set(ControlMode.Position,26624);
        
        ascenceurPourche = new TalonSRX(5);
        //addChild("AscenceurPourche",ascenceurPourche);
        //ascenceurPourche.setInverted(false);
        ascenceurPourche.set(ControlMode.PercentOutput,0);
        
        limitSwitch1 = new DigitalInput(8);
        addChild("Limit Switch 1",limitSwitch1);
        
        
        limitSwitch2 = new DigitalInput(9);
        addChild("Limit Switch 2",limitSwitch2);

        
        tombePourche = new Relay(0);
        addChild("TombePourche",tombePourche);
        
        SmartDashboard.putNumber("ALLO", 1234);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        SmartDashboard.putNumber("Talonsrx", ascenceur1.getSensorCollection().getQuadraturePosition());
        double valeur = SmartDashboard.getNumber("ALLO", 26624);
        ascenceur1.set(ControlMode.Position,valeur);
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

